function text(sel){return document.querySelector(sel)?.textContent?.trim()||undefined}
function meta(name){return document.querySelector(`meta[property="${name}"],meta[name="${name}"]`)?.content||undefined}
function jsonLd(){const out=[];for(const el of document.querySelectorAll('script[type="application/ld+json"]')){try{const j=JSON.parse(el.textContent||'null');const rows=Array.isArray(j)?j:[j];for(const r of rows){if(r?.['@type']==='Product')out.push(r);if(Array.isArray(r?.['@graph']))out.push(...r['@graph'].filter(x=>x?.['@type']==='Product'))}}catch{}}return out[0]}
function numberFrom(s){if(!s)return undefined;const m=String(s).replace(/,/g,'').match(/(?:USD|CAD|US\$|C\$|\$)?\s*([0-9]+(?:\.[0-9]{1,2})?)/i);return m?Number(m[1]):undefined}
function detectPack(title=''){const m=title.toLowerCase().match(/(?:pack|set|lot)\s*(?:of)?\s*(\d+)|\b(\d+)\s*(?:pack|pcs|pieces)\b|\bx\s*(\d+)\b/);return Number(m?.[1]||m?.[2]||m?.[3]||1)}
function cleanTitle(t=''){return String(t).replace(/\s*\|\s*eBay.*$/i,'').replace(/\s+-\s+eBay.*$/i,'').replace(/^Details about\s+/i,'').trim()}
function ebayItemId(){return location.pathname.match(/\/itm\/(?:[^/?#]+\/)?(\d{9,15})(?:[/?#]|$)/)?.[1]}
function extract(){const ld=jsonLd()||{};const offers=Array.isArray(ld.offers)?ld.offers[0]:ld.offers||{};const title=cleanTitle(ld.name||meta('og:title')||text('h1.x-item-title__mainTitle')||text('h1')||document.title);const price=numberFrom(offers.price)||numberFrom(meta('product:price:amount'))||numberFrom(text('[itemprop="price"]'))||numberFrom(text('.x-price-primary'))||numberFrom(text('.price'));const currency=offers.priceCurrency||meta('product:price:currency')||(/\.ca$/i.test(location.hostname)?'CAD':/\.com$/i.test(location.hostname)?'USD':undefined);const brand=typeof ld.brand==='string'?ld.brand:ld.brand?.name;const itemId=ebayItemId();return{sourceUrl:location.href,host:location.hostname,title,brand,sku:ld.sku,upc:ld.gtin12||ld.gtin13||ld.gtin14||ld.gtin,listingId:itemId,price,currency,packSize:detectPack(title),capturedAt:new Date().toISOString(),source:'BROWSER_COMPANION'}}
function scanPage(){return{products:[extract()],scanType:'GENERIC_PAGE'}}
chrome.runtime.onMessage.addListener((msg,_sender,send)=>{if(msg?.type==='PF_EXTRACT_PRODUCT'){const product=extract();send({ok:!!product.title,product});return true}if(msg?.type==='PF_SCAN_PAGE'){send({ok:true,...scanPage()});return true}});
