function text(sel){return document.querySelector(sel)?.textContent?.trim()||undefined}
function attr(sel,name){return document.querySelector(sel)?.getAttribute(name)||undefined}
function meta(name){return document.querySelector(`meta[property="${name}"],meta[name="${name}"]`)?.content||undefined}
function jsonLd(){const out=[];for(const el of document.querySelectorAll('script[type="application/ld+json"]')){try{const j=JSON.parse(el.textContent||'null');const rows=Array.isArray(j)?j:[j];for(const r of rows){if(r?.['@type']==='Product')out.push(r);if(Array.isArray(r?.['@graph']))out.push(...r['@graph'].filter(x=>x?.['@type']==='Product'))}}catch{}}return out[0]}
function numberFrom(s){if(!s)return undefined;const m=String(s).replace(/,/g,'').match(/(?:USD|CAD|US\$|C\$|\$)?\s*([0-9]+(?:\.[0-9]{1,2})?)/i);return m?Number(m[1]):undefined}
function detectPack(title=''){const m=title.toLowerCase().match(/(?:pack|set|lot)\s*(?:of)?\s*(\d+)|\b(\d+)\s*(?:pack|pcs|pieces)\b|\bx\s*(\d+)\b/);return Number(m?.[1]||m?.[2]||m?.[3]||1)}
function extract(){const ld=jsonLd()||{};const offers=Array.isArray(ld.offers)?ld.offers[0]:ld.offers||{};const title=ld.name||meta('og:title')||text('h1')||document.title;const price=numberFrom(offers.price)||numberFrom(meta('product:price:amount'))||numberFrom(text('[itemprop="price"]'))||numberFrom(text('.price'));
 const currency=offers.priceCurrency||meta('product:price:currency')||(/\.ca\b/i.test(location.hostname)?'CAD':undefined);
 const brand=typeof ld.brand==='string'?ld.brand:ld.brand?.name;const sku=ld.sku||text('[itemprop="sku"]');const upc=ld.gtin12||ld.gtin13||ld.gtin14||ld.gtin||undefined;
 return {sourceUrl:location.href,host:location.hostname,title,brand,sku,upc,price,currency,packSize:detectPack(title),image:typeof ld.image==='string'?ld.image:Array.isArray(ld.image)?ld.image[0]:meta('og:image'),capturedAt:new Date().toISOString(),source:'BROWSER_COMPANION'} }
chrome.runtime.onMessage.addListener((msg,_sender,send)=>{if(msg?.type==='PF_EXTRACT_PRODUCT'){send({ok:true,product:extract()});return true}if(msg?.type==='PF_SCAN_PAGE'){const products=[];for(const card of document.querySelectorAll('[itemtype*="Product"], [data-product-id], [data-sku], article')){const title=card.querySelector('h1,h2,h3,[itemprop="name"]')?.textContent?.trim();if(!title)continue;const price=numberFrom(card.querySelector('[itemprop="price"],.price,[class*="price"]')?.textContent);products.push({title,price,sku:card.getAttribute('data-sku')||undefined,productId:card.getAttribute('data-product-id')||undefined,sourceUrl:location.href,host:location.hostname,packSize:detectPack(title),capturedAt:new Date().toISOString(),source:'BROWSER_COMPANION_PAGE'})}send({ok:true,products});return true}});
