const result=document.getElementById('result');let lastResearch=null;
async function active(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});return tab}
async function ask(type,payload={}){const tab=await active();if(!tab?.id)throw new Error('No active tab');return chrome.tabs.sendMessage(tab.id,{type,...payload})}
async function cfg(){return chrome.storage.local.get({apiBase:'http://localhost:3000',authToken:'',cadUsdRate:0.73})}
async function post(path,body){const c=await cfg();const r=await fetch(c.apiBase+path,{method:'POST',headers:{'content-type':'application/json',...(c.authToken?{authorization:`Bearer ${c.authToken}`}:{})},body:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);return r.json()}
function show(v){result.textContent=v;chrome.storage.local.set({pfLastResult:v})}
function money(v){return v?.amount==null?'—':`${v.currency==='CAD'?'C$':v.currency==='USD'?'US$':'$'}${v.amount.toFixed(2)}`}
function demand(x){const rows=x.products||[],qty=rows.map(r=>r.quantitySold||0),multi=qty.filter(n=>n>=2).length,strong=qty.filter(n=>n>=10).length;if(strong>=3||multi>=6)return 'STRONG';if(multi>=3||rows.length>=10)return 'MODERATE';if(rows.length>=3)return 'WEAK';return 'NO PROVEN DEMAND'}
function researchText(x){const s=x.summary||{};return [`Demand: ${demand(x)}`,`Sample: ${Math.min(x.products?.length||0,20)} sold listings`,`Avg sold: ${money(s.averageSoldPrice)}`,`Sold range: ${s.soldPriceRange||'—'}`,`Avg shipping: ${money(s.averageShipping)}`,`Free shipping: ${s.freeShippingRate??'—'}%`,`Sellers: ${s.totalSellers??'—'}`,s.dateRange?`Period: ${s.dateRange}`:null].filter(Boolean).join('\n')}
async function saveResearch(x){lastResearch=x;await chrome.storage.local.set({pfLastResearch:x})}
async function init(){const saved=await chrome.storage.local.get({pfLastResearch:null,pfLastResult:'',sourceCost:'',shipCost:'',feeRate:'13.25',adRate:'0',cadUsdRate:'0.73'});lastResearch=saved.pfLastResearch;for(const id of ['sourceCost','shipCost','feeRate','adRate','cadUsdRate'])if(document.getElementById(id))document.getElementById(id).value=saved[id]??'';const tab=await active(),isResearch=/ebay\.(com|ca)\/sh\/research/i.test(tab?.url||'');document.getElementById('ebayPanel').classList.toggle('hidden',!isResearch);show(saved.pfLastResult||(lastResearch?researchText(lastResearch):isResearch?'eBay Product Research detected. Scan the page first.':'Ready.'))}
async function persistInputs(){const o={};for(const id of ['sourceCost','shipCost','feeRate','adRate','cadUsdRate'])o[id]=document.getElementById(id)?.value??'';await chrome.storage.local.set(o)}
document.getElementById('investigate').onclick=async()=>{try{show('Capturing source product…');const x=await ask('PF_EXTRACT_PRODUCT');await chrome.storage.local.set({pfLastSource:x.product});if(x.product?.price!=null){document.getElementById('sourceCost').value=x.product.price;await persistInputs()}show(`Source captured: ${x.product?.title||'product'}\nCost found: ${x.product?.price!=null?money({amount:x.product.price,currency:x.product.currency}):'not detected — enter manually'}\nSaved for comparison with eBay research.`)}catch(e){show('Error: '+e.message)}};
document.getElementById('scan').onclick=async()=>{try{show('Reading sold evidence…');const x=await ask('PF_SCAN_PAGE');if(x.scanType==='EBAY_PRODUCT_RESEARCH_DOM'){await saveResearch(x);show(researchText(x));return}show(`${x.products?.length||0} products found on this page.`)}catch(e){show('Error: '+e.message)}};
document.getElementById('profitCheck').onclick=async()=>{try{if(!lastResearch?.summary?.averageSoldPrice?.amount)throw new Error('Scan eBay Product Research first');await persistInputs();const c=await cfg(),rawSale=lastResearch.summary.averageSoldPrice.amount,saleCur=lastResearch.summary.averageSoldPrice.currency||'CAD',rate=Number(document.getElementById('cadUsdRate').value)||c.cadUsdRate||0.73,sale=saleCur==='CAD'?rawSale*rate:rawSale,cost=Number(document.getElementById('sourceCost').value),ship=Number(document.getElementById('shipCost').value),feePct=Number(document.getElementById('feeRate').value)/100,adPct=Number(document.getElementById('adRate').value)/100;if(!Number.isFinite(cost)||cost<0)throw new Error('Enter USD source cost');if(!Number.isFinite(ship)||ship<0)throw new Error('Enter USD shipping cost');const orderFee=sale>10?.40:.30,fees=sale*feePct+orderFee,ads=sale*adPct,profit=sale-fees-ads-ship-cost,margin=sale?profit/sale*100:0,roi=cost?profit/cost*100:0,targetProfit=Math.max(sale*.15,cost*.30),maxBuy=sale-fees-ads-ship-targetProfit,d=demand(lastResearch);let verdict='PASS';if(profit>0&&roi>=30&&margin>=15&&d==='STRONG')verdict='BUY';else if(profit>0&&roi>=20&&margin>=10&&d!=='NO PROVEN DEMAND')verdict='MAYBE';show([`${verdict} — ${d} EBAY DEMAND`,`eBay avg sold: ${saleCur==='CAD'?`C$${rawSale.toFixed(2)} → `:''}US$${sale.toFixed(2)}`,saleCur==='CAD'?`CAD→USD rate used: ${rate}`:null,`Wholesale/source cost: US$${cost.toFixed(2)}`,`eBay fee est.: US$${fees.toFixed(2)} (${(feePct*100).toFixed(2)}% + order fee)`,adPct?`Promoted listing: US$${ads.toFixed(2)}`:null,`Your shipping: US$${ship.toFixed(2)}`,`PROFIT: US$${profit.toFixed(2)} / unit`,`Margin: ${margin.toFixed(1)}%`,`ROI: ${roi.toFixed(1)}%`,`Max source cost: US$${Math.max(0,maxBuy).toFixed(2)}`].filter(Boolean).join('\n'))}catch(e){show('Profit check: '+e.message)}};
document.getElementById('ebayOne').onclick=async()=>{try{const query=document.getElementById('ebayQuery').value.trim();if(!query)throw new Error('Enter a product, UPC, SKU or search term');show('Running eBay Product Research…');await ask('PF_EBAY_RESEARCH_ONE',{query});show(`Search loaded: ${query}\nNow click SCAN THIS PAGE.`)}catch(e){show('eBay research error: '+e.message)}};
document.getElementById('ebayCurrent').onclick=()=>document.getElementById('scan').click();document.getElementById('ebayRunBatch').onclick=async()=>{try{const queries=document.getElementById('ebayBatch').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!queries.length)throw new Error('Enter at least one product');show(`Starting batch of ${queries.length}…`);const x=await ask('PF_EBAY_RESEARCH_BATCH',{queries});show(`Batch finished: ${x?.results?.filter(r=>r.ok).length??0}/${queries.length}.`)}catch(e){show('Batch error: '+e.message)}};document.getElementById('settings').onclick=()=>chrome.runtime.openOptionsPage();init();