async function configureSidePanel(){await chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true});}
const DEFAULT_SCOUT={enabled:false,status:'OFF',queue:[],processed:0,opportunities:[],current:null,lastRun:null};
chrome.runtime.onInstalled.addListener(async()=>{const c=await chrome.storage.local.get(['apiBase','scout']);const patch={};if(!c.apiBase)patch.apiBase='http://localhost:3000';if(!c.scout)patch.scout=DEFAULT_SCOUT;if(Object.keys(patch).length)await chrome.storage.local.set(patch);await configureSidePanel();});
chrome.runtime.onStartup.addListener(()=>configureSidePanel().catch(()=>{}));
function isEbay(url=''){try{const h=new URL(url).hostname.toLowerCase();return h==='ebay.com'||h.endsWith('.ebay.com')||h==='ebay.ca'||h.endsWith('.ebay.ca')}catch{return false}}
function isAmazon(url=''){try{const h=new URL(url).hostname.toLowerCase();return h==='amazon.com'||h.endsWith('.amazon.com')||h==='amazon.ca'||h.endsWith('.amazon.ca')}catch{return false}}
function isItem(url=''){return isEbay(url)&&/\/itm\//i.test(url)}
async function syncPanel(tabId,url){if(!tabId)return;const supported=isEbay(url)||isAmazon(url);await chrome.sidePanel.setOptions({tabId,enabled:supported,path:'popup.html'}).catch(()=>{});if(isEbay(url))await chrome.runtime.sendMessage({type:'PF_ACTIVE_EBAY_TAB',tabId,url,isItem:isItem(url)}).catch(()=>{});}
chrome.tabs.onUpdated.addListener((tabId,changeInfo,tab)=>{if(changeInfo.status==='complete'||changeInfo.url){syncPanel(tabId,changeInfo.url||tab.url);if(changeInfo.status==='complete'&&isAmazon(tab.url))captureAmazon(tabId).catch(()=>{});}});
chrome.tabs.onActivated.addListener(async({tabId})=>{const tab=await chrome.tabs.get(tabId).catch(()=>null);if(tab){syncPanel(tabId,tab.url);if(isAmazon(tab.url))captureAmazon(tabId).catch(()=>{});}});
async function getScout(){const x=await chrome.storage.local.get('scout');return {...DEFAULT_SCOUT,...(x.scout||{})};}
async function saveScout(s){s.lastRun=new Date().toISOString();await chrome.storage.local.set({scout:s});chrome.runtime.sendMessage({type:'PF_SCOUT_UPDATE',scout:s}).catch(()=>{});}
function cleanTitle(t=''){return t.replace(/\s+/g,' ').replace(/Amazon\.[a-z.]+\s*:\s*/i,'').trim().slice(0,180)}
async function enqueueAmazon(p){const s=await getScout();if(!s.enabled||!p?.title)return;const title=cleanTitle(p.title);if(!title)return;const key=p.asin||title.toLowerCase();if(s.queue.some(x=>x.key===key)||s.opportunities.some(x=>x.key===key)||s.current?.key===key)return;s.queue.push({key,title,asin:p.asin||'',amazonPrice:p.price||'',amazonUrl:p.url||'',stage:'QUEUED',capturedAt:new Date().toISOString()});s.status='AMAZON CAPTURED';await saveScout(s);await processQueue();}
async function captureAmazon(tabId){const s=await getScout();if(!s.enabled)return;const r=await chrome.scripting.executeScript({target:{tabId},func:()=>{const asin=(location.pathname.match(/\/(?:dp|gp\/product)\/([A-Z0-9]{10})/i)||[])[1]||document.querySelector('[data-asin]')?.getAttribute('data-asin')||'';const title=(document.querySelector('#productTitle')?.textContent||document.querySelector('#title')?.textContent||document.querySelector('h1')?.textContent||document.title||'').trim();const price=(document.querySelector('#corePrice_feature_div .a-price .a-offscreen')?.textContent||document.querySelector('.a-price .a-offscreen')?.textContent||'').trim();return {asin,title,price,url:location.href};}}).catch(()=>null);const p=r?.[0]?.result;if(p)await enqueueAmazon(p);}
async function findResearchTab(){const tabs=await chrome.tabs.query({url:['https://*.ebay.com/sh/research*','https://*.ebay.ca/sh/research*']});return tabs[0]||null;}
async function processQueue(){const s=await getScout();if(!s.enabled||s.current||!s.queue.length)return;const item=s.queue.shift();s.current=item;s.status='RESEARCHING EBAY';await saveScout(s);let tab=await findResearchTab();if(!tab){tab=await chrome.tabs.create({url:'https://www.ebay.com/sh/research?marketplace=EBAY-US&keywords='+encodeURIComponent(item.title),active:false});}else{await chrome.tabs.update(tab.id,{url:'https://www.ebay.com/sh/research?marketplace=EBAY-US&keywords='+encodeURIComponent(item.title),active:false});}
setTimeout(async()=>{const now=await getScout();if(now.current?.key===item.key){now.current=null;now.processed++;now.status=now.queue.length?'QUEUED':'WAITING FOR AMAZON';await saveScout(now);await processQueue();}},15000);}
chrome.runtime.onMessage.addListener((m,sender,sendResponse)=>{(async()=>{if(m?.type==='PF_SCOUT_TOGGLE'){const s=await getScout();s.enabled=!!m.enabled;s.status=s.enabled?'WAITING FOR AMAZON':'OFF';if(!s.enabled)s.current=null;await saveScout(s);if(s.enabled){const tabs=await chrome.tabs.query({active:true,currentWindow:true});const tab=tabs[0];if(tab&&isAmazon(tab.url))await captureAmazon(tab.id);await processQueue();}sendResponse({ok:true,scout:s});return;}if(m?.type==='PF_AMAZON_PRODUCT'){await enqueueAmazon(m.product);sendResponse({ok:true});return;}if(m?.type==='PF_SCOUT_GET'){sendResponse({ok:true,scout:await getScout()});return;}if(m?.type==='PF_SCOUT_EBAY_RESULT'&&m.result){const s=await getScout();const item=s.current;if(item){const r={...item,...m.result,key:item.key,researchedAt:new Date().toISOString()};if((r.observedUnits||0)>0)s.opportunities.unshift(r);s.current=null;s.processed++;s.status=s.queue.length?'QUEUED':'WAITING FOR AMAZON';await saveScout(s);await processQueue();}sendResponse({ok:true});return;}sendResponse({ok:false});})().catch(e=>sendResponse({ok:false,error:String(e)}));return true;});