async function configureSidePanel(){await chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true});}
const DEFAULT_SCOUT={enabled:false,status:'OFF',queue:[],processed:0,opportunities:[],current:null,lastRun:null,workerTabId:null,ebaySession:'UNKNOWN'};
chrome.runtime.onInstalled.addListener(async()=>{const c=await chrome.storage.local.get(['apiBase','scout']);const patch={};if(!c.apiBase)patch.apiBase='http://localhost:3000';if(!c.scout)patch.scout=DEFAULT_SCOUT;if(Object.keys(patch).length)await chrome.storage.local.set(patch);await configureSidePanel();});
chrome.runtime.onStartup.addListener(async()=>{await configureSidePanel().catch(()=>{});const s=await getScout();if(s.enabled)await ensureResearchWorker(false).catch(()=>{});});
function isEbay(url=''){try{const h=new URL(url).hostname.toLowerCase();return h==='ebay.com'||h.endsWith('.ebay.com')||h==='ebay.ca'||h.endsWith('.ebay.ca')}catch{return false}}
function isAmazon(url=''){try{const h=new URL(url).hostname.toLowerCase();return h==='amazon.com'||h.endsWith('.amazon.com')||h==='amazon.ca'||h.endsWith('.amazon.ca')}catch{return false}}
function isResearch(url=''){return isEbay(url)&&/\/sh\/research/i.test(url)}
function isSignin(url=''){return isEbay(url)&&/(signin|login|auth)/i.test(url)}
async function syncPanel(tabId,url){if(!tabId)return;await chrome.sidePanel.setOptions({tabId,enabled:isEbay(url)||isAmazon(url),path:'popup.html'}).catch(()=>{});}
chrome.tabs.onUpdated.addListener((tabId,changeInfo,tab)=>{if(changeInfo.status==='complete'||changeInfo.url){syncPanel(tabId,changeInfo.url||tab.url);if(changeInfo.status==='complete'&&isAmazon(tab.url))captureAmazon(tabId).catch(()=>{});if(changeInfo.status==='complete'&&isResearch(tab.url))markWorker(tabId,'CONNECTED').catch(()=>{});if(changeInfo.status==='complete'&&isSignin(tab.url))markWorker(tabId,'LOGIN REQUIRED').catch(()=>{});}});
chrome.tabs.onActivated.addListener(async({tabId})=>{const tab=await chrome.tabs.get(tabId).catch(()=>null);if(tab){syncPanel(tabId,tab.url);if(isAmazon(tab.url))captureAmazon(tabId).catch(()=>{});}});
async function getScout(){const x=await chrome.storage.local.get('scout');return {...DEFAULT_SCOUT,...(x.scout||{})};}
async function saveScout(s){s.lastRun=new Date().toISOString();await chrome.storage.local.set({scout:s});chrome.runtime.sendMessage({type:'PF_SCOUT_UPDATE',scout:s}).catch(()=>{});}
async function markWorker(tabId,state){const s=await getScout();s.workerTabId=tabId;s.ebaySession=state;if(state==='LOGIN REQUIRED')s.status='EBAY LOGIN REQUIRED';await saveScout(s);}
function cleanTitle(t=''){return t.replace(/\s+/g,' ').replace(/\s*:\s*Amazon\.(?:com|ca).*$/i,'').replace(/Amazon\.[a-z.]+\s*:\s*/i,'').trim().slice(0,180)}
async function enqueueAmazon(p){const s=await getScout();if(!s.enabled||!p?.title)return;const title=cleanTitle(p.title);if(!title)return;const key=p.asin||title.toLowerCase();if(s.queue.some(x=>x.key===key)||s.opportunities.some(x=>x.key===key)||s.current?.key===key)return;s.queue.push({key,title,asin:p.asin||'',amazonPrice:p.price||'',amazonUrl:p.url||'',capturedAt:new Date().toISOString()});s.status='AMAZON CAPTURED';await saveScout(s);await processQueue();}
async function captureAmazon(tabId){const s=await getScout();if(!s.enabled)return;const r=await chrome.scripting.executeScript({target:{tabId},func:()=>{const asin=(location.pathname.match(/\/(?:dp|gp\/product)\/([A-Z0-9]{10})/i)||[])[1]||document.querySelector('[data-asin]')?.getAttribute('data-asin')||'';const title=(document.querySelector('#productTitle')?.textContent||document.querySelector('#title')?.textContent||document.querySelector('h1')?.textContent||document.title||'').replace(/\s+/g,' ').trim();const price=(document.querySelector('#corePrice_feature_div .a-price .a-offscreen')?.textContent||document.querySelector('.a-price .a-offscreen')?.textContent||'').trim();return {asin,title,price,url:location.href};}}).catch(()=>null);if(r?.[0]?.result)await enqueueAmazon(r[0].result);}
async function ensureResearchWorker(makeVisible=false){let s=await getScout();let tab=s.workerTabId?await chrome.tabs.get(s.workerTabId).catch(()=>null):null;if(!tab){const tabs=await chrome.tabs.query({url:['https://*.ebay.com/sh/research*','https://*.ebay.ca/sh/research*']});tab=tabs[0]||null;}if(!tab){tab=await chrome.tabs.create({url:'https://www.ebay.com/sh/research?marketplace=EBAY-US',active:makeVisible});}else if(makeVisible){await chrome.tabs.update(tab.id,{active:true});}
s.workerTabId=tab.id;s.ebaySession=isSignin(tab.url)?'LOGIN REQUIRED':(isResearch(tab.url)?'CONNECTED':'CHECKING');await saveScout(s);return tab;}
async function finishResearch(item,data){const s=await getScout();if(s.current?.key!==item.key)return;const rows=data?.rows||data?.products||[];const observedUnits=rows.reduce((n,r)=>n+(Number(r.quantitySold)||0),0);const r={...item,...data,key:item.key,observedUnits,researchedAt:new Date().toISOString()};if(observedUnits>0)s.opportunities.unshift(r);s.current=null;s.processed++;s.status=s.queue.length?'QUEUED':'WAITING FOR AMAZON';await saveScout(s);await processQueue();}
async function runResearch(tabId,item,attempt=0){if(attempt>20)throw new Error('eBay Product Research worker did not become ready');const tab=await chrome.tabs.get(tabId).catch(()=>null);if(!tab)throw new Error('eBay worker closed');if(isSignin(tab.url)){await markWorker(tabId,'LOGIN REQUIRED');throw new Error('EBAY_LOGIN_REQUIRED');}try{const res=await chrome.tabs.sendMessage(tabId,{type:'PF_EBAY_RESEARCH_ONE',query:item.title});if(!res?.ok)throw new Error(res?.error||'eBay research failed');await markWorker(tabId,'CONNECTED');await finishResearch(item,res.data);}catch(e){if(String(e).includes('EBAY_LOGIN_REQUIRED'))throw e;await new Promise(r=>setTimeout(r,1000));return runResearch(tabId,item,attempt+1);}}
async function processQueue(){const s=await getScout();if(!s.enabled||s.current||!s.queue.length)return;const item=s.queue.shift();s.current=item;s.status='RESEARCHING EBAY';await saveScout(s);const tab=await ensureResearchWorker(false);runResearch(tab.id,item).catch(async e=>{const now=await getScout();if(now.current?.key===item.key){if(String(e).includes('EBAY_LOGIN_REQUIRED')){now.queue.unshift(item);now.current=null;now.status='EBAY LOGIN REQUIRED';now.ebaySession='LOGIN REQUIRED';}else{item.error=String(e?.message||e);now.current=null;now.processed++;now.status=now.queue.length?'QUEUED':'WAITING FOR AMAZON';}await saveScout(now);if(now.enabled&&now.status!=='EBAY LOGIN REQUIRED')await processQueue();}});}
chrome.runtime.onMessage.addListener((m,sender,sendResponse)=>{(async()=>{if(m?.type==='PF_SCOUT_TOGGLE'){const s=await getScout();s.enabled=!!m.enabled;s.status=s.enabled?'WAITING FOR AMAZON':'OFF';if(!s.enabled)s.current=null;await saveScout(s);if(s.enabled){await ensureResearchWorker(false);const tabs=await chrome.tabs.query({active:true,currentWindow:true});if(tabs[0]&&isAmazon(tabs[0].url))await captureAmazon(tabs[0].id);await processQueue();}sendResponse({ok:true,scout:await getScout()});return;}if(m?.type==='PF_AMAZON_PRODUCT'){await enqueueAmazon(m.product);sendResponse({ok:true});return;}if(m?.type==='PF_SCOUT_GET'){sendResponse({ok:true,scout:await getScout()});return;}if(m?.type==='PF_OPEN_EBAY_WORKER'){const tab=await ensureResearchWorker(true);sendResponse({ok:true,tabId:tab.id});return;}if(m?.type==='PF_RETRY_EBAY'){const s=await getScout();s.ebaySession='CHECKING';s.status='QUEUED';await saveScout(s);await ensureResearchWorker(false);await processQueue();sendResponse({ok:true});return;}sendResponse({ok:false});})().catch(e=>sendResponse({ok:false,error:String(e)}));return true;});